spring:
  application:
    name: demo-services
  datasource:
    driver-class-name: com.informix.jdbc.IfxDriver
    password: XXX
    url: jdbc:informix-sqli://d0102.reecenet.org:8962/eunice:INFORMIXSERVER=trstst2_nt;IFX_LOCK_MODE_WAIT=-1;IFX_ISOLATION_LEVEL=1U;JDBCTEMP=/tmp
    username: xxx
  jpa:
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    bus:
      enabled: true
      refresh:
        enabled: true

server:
  port: 8090
  servlet:
    context-path: /demo-service

info:
  environment:
    instance: au
    system: inmemory

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
  security:
    enabled: false
