--- # -----------------------------------------------------------------------------------------------
# -----------------------------------------------------------------------------------------------
# Spring
spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.jms.JmsAutoConfiguration
  application:
    name: organisation-service
  main:
    banner-mode: "off"
  http:
    encoding:
      enabled: true
      charset: UTF-8
      force-response: true

# -----------------------------------------------------------------------------------------------
# Web Server
# -----------------------------------------------------------------------------------------------
server:
  servlet:
    context-path: /organisation-servicess
  port: ${override.port:8091}

# -----------------------------------------------------------------------------------------------
# Spring Boot Actuator
# -----------------------------------------------------------------------------------------------
management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            request: true
      percentiles:
        http:
          server:
            request: "0.95,0.99,0.999"
  security:
    enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka

# -----------------------------------------------------------------------------------------------
# Swagger API configuration
# -----------------------------------------------------------------------------------------------
swagger:
  base-package-to-scan: au.com.reece.organisation.controller
  api-info:
    team-name: Inventory Team
    title: Organisation Service REST APIII
    description: Provides organisation information
