server:
  port: 8060

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - gateway
          - "*"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka

spring:
  application:
    name: spring-cloud-gateway
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: organisationServices
          uri: lb://ORGANISATION-SERVICE
          predicates:
            - Path=/organisation-service/**
          filters:
            - CustomFilter
        - id: odataServices
          uri: lb://DEMO-SERVICES
          predicates:
            - Path=/demo-service/**
          filters:
            - CustomFilter
        - id: pos
          uri: https://trstst08.reecenet.org
          predicates:
            - Path=/pos/**
          filters:
            - CustomFilter

    bus:
      enabled: true
      refresh:
        enabled: true
